name: github_sign_in
description: Sign In With GitHub
version: 0.0.5-dev.4
homepage: https://github.com/dotronglong/dart-github-sign-in

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  # flutter_webview_plugin: ^0.3.11
  webview_flutter:  ^4.0.7
  url_launcher: ^6.0.17
